#!/bin/bash

sudo apt update && sudo apt upgrade -y
# apt packages
sudo apt install \
    curl\
    vim\
    git\
    zsh\
    cmake\
    golang-go\
    python3-dev\
    build-essential\
    chromium-browser\
    -y

git config --global user.email "shanemcdman@gmail.com"
git config --global user.name "Shane McDonough"


# install rust
curl https://sh.rustup.rs | sh

# clone dotfiles
git clone https://github.com/KermitPurple/dotfiles.git $HOME/dotfiles

# create symbolic links
ln -s $HOME/dotfiles/vim $HOME/.vim
ln -s $HOME/dotfiles/zsh/zshrc $HOME/.zshrc
ln -s $HOME/dotfiles/zsh/zshenv $HOME/.zshenv
ln -s $HOME/dotfiles/skhd/skhdrc $HOME/.skhdrc
ln -s $HOME/dotfiles/nvim/ $HOME/.config/nvim

# make vim trash files
mkdir $HOME/dotfiles/vim/{trash,views}

# install vim plugins
vim -c "PlugInstall" \
    -c "qa!"
# below requires go and cmake
$HOME/dotfiles/vim/plugged/YouCompleteMe/install.py --all

# pip3 install virtualenv

# reinstall script requirements
# . ~/.zshenv
# $HOME/dotfiles/clone_reqs
