#!/bin/sh

# homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# xcode commandline tools
xcode-select --install

# brew packages
brew install \
    vim\
    skhd\
    rust\
    raylib\
    ffmpeg\
    dropbox\
    spotify\
    discord\
    openjdk\
    python@3.10\
    util-linux\
    visual-studio-code

# clone dotfiles
git clone git@github.com:KermitPurple/dotfiles.git

# create symbolic links
ln -s $HOME/dotfiles/vim $HOME/.vim
ln -s $HOME/dotfiles/zsh/zshrc $HOME/.zshrc
ln -s $HOME/dotfiles/zsh/zshenv $HOME/.zshenv
ln -s $HOME/dotfiles/skhd/skhdrc $HOME/.skhdrc

# make vim trash files
mkdir $HOME/dotfiles/vim/trash $HOME/dotfiles/vim/views

# install vim plugins
vim -c "PlugInstall" \
    -c "qa!"
