#!/bin/bash
# open the man page of the arguments in chrome
# first arg: [optional] man section number
# second arg: man page to find
# flags:
#   -w - open in new window instead of new tab

function help_text(){
    while IFS= read -r line; do
        echo "$line"
    done <<-EOF
USAGE: chrome_man [section_number] page
  - flags:
    -w - open in new window instead of new tab
EOF
}

function try_url(){
    curl -sLf "$1" >/dev/null
    code=$?
    if [[ $code = 0 ]]; then # if page exists
        $chrome_fn "$1" # open page
    else
        return $code
    fi
}

chrome_fn="chrome"
while [[ $# > 0 ]]; do
    case "$1" in
        [0123456789]*)
            i=$1
            ;;
        -w)
            chrome_fn="new_chrome"
            ;;
        *)
            page=`encode_url "$1"`
            ;;
    esac
    shift
done
if [[ ! -z "$i" && ! -z "$page" ]]; then # i and page aren't blank
    try_url "https://man7.org/linux/man-pages/man$i/$page.$i.html"
elif [[ -z "$i" && ! -z "$page" ]]; then # i is blank
    for i in `seq 8`; do
        try_url "https://man7.org/linux/man-pages/man$i/$page.$i.html"
        [[ $? = 0 ]] && break
    done
else # page is blank
    >&2 echo "A page must be passed"
    >&2 help_text
    exit 1
fi
