#!/bin/sh
username="KermitPurple"
repo="$1"
shift # remove first arg

case "$repo" in
    *.git);;
    *) repo="$repo.git";; # add .git if it isn't there
esac
git clone "git@github.com:$username/$repo" "$@"
