#!/bin/bash
# clone requirements for scripts aliases and functions

mkdir -p $CODING_DIR/python $CODING_DIR/c++ $CODING_DIR/rust
locations="$DOTFILES_DIR/zsh/funcs.zsh $DOTFILES_DIR/zsh/alias.zsh $DOTFILES_DIR/scripts/*"
first=0
repo=
dir=
branch=
build=

clone_req(){
    # echo $repo
    # echo $dir
    # echo $branch
    # echo $build
    if [[ ! -z $repo && ! -z $dir && ! -d $dir ]]; then
        git clone "$repo" "$dir"
        cd $dir
        [[ -z "$branch" ]] || git checkout $branch
        [[ -z "$build" ]] || /bin/bash -c "$build"
    fi
}

while read line;do
    if [[ $line = 'repo: '* ]]; then 
        if [[ $first = 1 ]]; then
            clone_req
        else
            first=1
        fi
        repo=$(echo $line|sed 's/repo: //')
        dir=
        branch=
        build=
    else
        case "$line" in
            dir:*)
                dir=$(/bin/bash -c "echo $(echo $line|sed 's/dir: //')")
                ;;
            branch:*)
                branch=$(echo $line|sed 's/branch: //')
                ;;
            build:*)
                build=$(echo $line|sed 's/build: //')
                ;;
        esac
    fi
done <<< "$(sed -E '/^# (repo|dir|build|branch):/!d;s/# //' $locations)"
clone_req
