#!/bin/zsh
# close an iterm tab
if [[ `osascript -e "return application \"Iterm\" is running"` = "false" ]]; then
    >&2 echo "Iterm is not open"
    return 1
else
    osascript -e\
"tell application \"iterm2\"
    tell current window
        close current tab
    end tell
    if (count windows) < 1
        quit
    end if
end tell"
fi
