#!/bin/zsh
# close an chrome tab
if [[ `osascript -e "return application \"Google Chrome\" is running"` = "false" ]]; then
    >&2 echo "Google Chrome is not open"
    return 1
else
    osascript -e\
"tell application \"Google Chrome\"
    if (count windows) < 1
        quit
    else
        tell front window
            close active tab
        end tell
    end if
end tell"
fi
