#!/bin/zsh
# close an iterm tab
if [[ $(osascript -e "return application \"Iterm\" is running") = "false" ]]; then
    >&2 echo "Iterm is not open"
    return 1
else
    osascript -e\
"tell application \"iterm2\"
    if (count windows) < 1
        quit
    else
        tell current window
            close current tab
        end tell
    end if
end tell"
fi
