#!/bin/zsh
# close an iterm window
if [[ `osascript -e "return application \"Iterm\" is running"` = "false" ]]; then
    >&2 echo "Iterm is not open"
    return 1
else
    osascript -e\
"tell application \"iterm2\"
    close current window
end tell"
fi
