#!/bin/zsh
# close an iterm window
if [[ `osascript -e "return application \"Iterm\" is running"` = "false" ]]; then
    >&2 echo "Iterm is not open"
    return 1
else
    osascript -e\
"tell application \"iterm2\"
    if (count windows) < 1
        quit
    else
        close current window
    end if
end tell"
fi
