#!/bin/sh

chapter_number="$(head -n 1 "$CSM_CH_PATH")"
[ -z "$chapter_number" ] && chapter_number='1'
base_url='https://ww2.chainsaw-man-manga.online/manga/chainsaw-man-chapter-'
site_url="$base_url$chapter_number/"

if [ -z "$(curl "$site_url" -s)" ]; then
    echo "There is not a new chainsaw man chapter😔"
    exit 1
else
    echo "There is a new chainsaw man chapter!🎉"
    chrome "$site_url"
    echo "$chapter_number + 1" | bc > "$CSM_CH_PATH"
fi
