#!/usr/bin/env python3
from urllib.parse import unquote_plus
from sys import argv, stdin, stderr

_ = argv.pop(0)
input_string = ' '.join(argv)
if not input_string:
    input_string = stdin.read()
print(unquote_plus(input_string))
