#!/usr/bin/env python3
# pip3 install urllib
from urllib.parse import quote_plus
from sys import argv, stdin, stderr

_ = argv.pop(0)
input_string = ' '.join(argv)
if not input_string:
    input_string = stdin.read()
print(quote_plus(input_string))
