#!/bin/sh

number=false
for arg; do
    case "$arg" in
        -n|--number)
            number=true
            ;;
    esac
done

stty raw
read -rn1 character
stty cooked
if $number; then
    printf "%d\n" "'$character'" # print the number value of the character
else
    echo "$character"
fi
