#!/bin/sh

locations=("$CODING_DIR" "$DOTFILES_DIR") # locations to search
for location in $locations; do # cycle over locations
    for repo in `find $location -name .git -not -path '*/plugged/*'`; do # cylce over repos in locations
        cd $repo/.. # go to repo
        pwd # print location
        git $*
    done
done
