#!/bin/sh
# call git command over all (most) of my get repos
# This is done mostly because I frequently forget to push

prog="mega_git"

die(){
    >&2 echo "$prog: \033[1;31merror:\033[0m \033[1;37m$*\033[0m" # print colored output to sterr
    exit 1
}

show_help(){
    while IFS= read -r line; do
        printf "%s\n" "$line"
    done <<-EOF
$prog SUBCMD [flags]
  Call "git SUBCMD" on each repo
  flags:
    --async       - Run each git command asyncronously; cannot be run with --less
    --no-async    - Run each git command sequentally; default
    --less        - Pipe output of git command into less
    --no-less     - Do not pipe output into less; default
    --exec CMD    - Pipe the output of each git command into CMD
    --interactive - Run interactively
    --help, -h    - print this output
EOF
}

less=false
async=false
exec_f=false
interactive=false
exec_arg=""
args=""
while [ $# -gt 0 ]; do
    case $1 in
        --async)
            async=true
            ;;
        --no-async)
            async=false
            ;;
        --less)
            less=true
            ;;
        --no-less)
            less=false
            ;;
        --interactive)
            interactive=true
            ;;
        --exec)
            exec_f=true
            if [ $# -gt 1 ]; then
                shift
                exec_arg="$1"
            else
                die "--exec flag was not passed an arg"
            fi
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            args="$args $1"
            ;;
    esac
    shift
done
[ -z "$args" ] && die "no git args passed"
cmd="git $args"
repos=$(find "$CODING_DIR" "$DOTFILES_DIR" -name .git ! -path '*/plugged/*')
for repo in $repos; do
    cd "$repo/.." || die "Could not go to $repo/.." # go to repo
    if $less; then
        if ! $exec_f; then
            (pwd; $cmd) | less # run git command and output to less
        else
            (pwd; ($cmd | $exec_arg)) | less
        fi
    elif $async && ! $exec_f; then
        $cmd & # call git command asyncronus
    elif ! $async && $exec_f; then
        $cmd | $exec_arg
    elif $async && $exec_f; then
        ($cmd | $exec_arg) &
    else
        echo "----------------------------------------------------------------------------------"
        pwd # print location
        $cmd # call git commadn
    fi
    if $interactive; then
        $SHELL
    fi
done
