#!/bin/sh
# open a new chrome window
homepage="$SEARCH_ENGINE"
app="Google Chrome"
location="$*"
if "$(osascript -e"return application \"$app\" is running")"; then
    [ -z "$location" ] && location="$homepage" # if location is null set to homepage
    osascript -e\
"tell application \"$app\"
    make new window
    open location \"$location\"
end tell"
else
    chrome "$location"
fi
