#!/bin/zsh
# open a new tab in iterm
# first arg is a path [optional]
# other args are the command passed to the terminal
# https://gist.github.com/vyder/96891b93f515cb4ac559e9132e1c9086
cmd=""
dir="$PWD"
args="$@"
if [ -d "$1" ]; then # if the first argument is a file
    dir="$1"
    args="${@:2}"
fi
if [ -n "$args" ]; then
    cmd="; $args"
fi
if [ `osascript -e"return application \"iterm2\" is running"` = 'true' ]; then
    osascript -e\
"tell application \"iterm2\"
    activate
    tell current window
        set newTab to (create tab with default profile)
        tell current session of newTab
            write text \"cd '$dir'$cmd\"
        end tell
    end tell
end tell"
else
    open -aIterm
    sleep 0.4
    osascript -e\
"tell application \"iterm2\"
    tell current window
        tell current tab
            tell current session
                write text \"cd '$dir'$cmd\"
            end tell
        end tell
    end tell
end tell"
fi
