#!/bin/sh
# gets url from listed of stored urls
# opens it in a new chrome tab
# removes first element
if [ ! -e "$CHROME_STASH" ] ||  [ -z "$(cat "$CHROME_STASH")" ]; then
    >&2 echo "Stash of popped tabs empty"
    exit 1
fi
chrome "$(sed -n '1p' "$CHROME_STASH")"
sed -i '' '1d' "$CHROME_STASH"
