#!/bin/zsh
# git@github.com:KermitPurple/ROTN.git
py_file="$CODING_DIR/python/ROTN/main.py"
if [ -t 0 ]; then # if running interactive
    $py_file $*
else # if using "|" or "<"
    $py_file $* -f /dev/stdin
fi

