#!/bin/sh
try_url(){
    curl -sLf "$1" >/dev/null
    code=$?
    if [ $code = 0 ]; then # if page exists
        chrome "$1" # open page
    else
        return $code
    fi
}

url="https://docs.rs"
if [ -n "$*" ]; then
    crate="$(encode_url "$*")"
    try_url "$url/$crate/latest/$crate" || chrome "$url/releases/search?query=$crate"
else
    chrome "$url"
fi
