#!/bin/zsh
# run passed arguments in the background and silenced
if [[ $# -lt 1 ]]; then
    print "Invalid number of arguments: $#"
    return 1
fi
setopt LOCAL_OPTIONS NO_NOTIFY NO_MONITOR
("$@" 2>&1 > /dev/null & disown) 2> /dev/null
return 0
