# source the cargo environment for rust
. "$HOME/.cargo/env"

# add util-linux bins to path
# to reinstall do brew install util-linux
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"

# Directories
export NOTE_FOLDER="$HOME/dropbox/note_folder"
export DOTFILES_DIR="$HOME/dotfiles"
export SCHOOL_DIR="$HOME/dropbox/school/fall2021"
export CODING_DIR="$HOME/coding"
export TEMP_DIR="$HOME/temp"
export SCRIPT_DIR="$DOTFILES_DIR/scripts"

# editing fpath
export fpath=(
/opt/homebrew/share/zsh/site-functions
"${fpath[@]}"
)

# add scripts to path
export PATH="$PATH:$SCRIPT_DIR"

# show dotfiles in fzf
export FZF_DEFAULT_COMMAND="find . -type f"

# the editor of choice
export EDITOR="$HOMEBREW_PREFIX/bin/vim"
