# source the cargo environment for rust
. "$HOME/.cargo/env"

# add util-linux bins to path
# to reinstall do brew install util-linux
export PATH="/opt/homebrew/opt/util-linux/bin:$PATH"
export PATH="/opt/homebrew/opt/util-linux/sbin:$PATH"

# Global Environment variables
export NOTE_FOLDER="$HOME/dropbox/note_folder"
export DOTFILES_DIR="$HOME/dotfiles"
export SCHOOL_DIR="$HOME/dropbox/school/fall2021"
export CODING_DIR="$HOME/coding"
export TEMP_DIR="$HOME/temp"
export ZDOTDIR="$DOTFILES_DIR/zsh"

# show dotfiles in fzf
export FZF_DEFAULT_COMMAND="find . -type f"

# the editor of choice
export EDITOR="/opt/homebrew/bin/vim"

# source zshrc
. "$DOTFILES_DIR/zsh/zshrc"
