# allow for colors
autoload -U colors && colors

# import other zsh files
. "$DOTFILES_DIR/zsh/alias.zsh"
. "$DOTFILES_DIR/zsh/funcs.zsh"
. "$DOTFILES_DIR/zsh/load_znap.zsh"

# set custom prompt
set_prompt
